package com.conestoga.lifetracker

import com.conestoga.lifetracker.data.entity.NoteEntity
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNotNull
import org.junit.Test

/**
 * Unit tests for the NoteEntity data class.
 * NoteEntity is the Room database entity for persisting notes.
 * Tests cover positive, negative, and edge cases for field storage and equality.
 */
class NoteEntityTest {

    /**
     * Test Case 1: Positive case - Full initialization stores all fields
     * Verifies that all constructor parameters are stored correctly
     */
    @Test
    fun testNoteEntityFullInitialization() {
        // Arrange & Act
        val entity = NoteEntity(id = 5, title = "Meeting Notes", createdAt = 1700000000000L)

        // Assert
        assertEquals("ID should be 5", 5, entity.id)
        assertEquals("Title should match", "Meeting Notes", entity.title)
        assertEquals("CreatedAt should match", 1700000000000L, entity.createdAt)
    }

    /**
     * Test Case 2: Positive case - Default id is 0 (auto-generated by Room)
     * Verifies Room's autoGenerate default value
     */
    @Test
    fun testNoteEntityDefaultId_IsZero() {
        // Act
        val entity = NoteEntity(title = "Default ID Note")

        // Assert
        assertEquals("Default id should be 0 before Room inserts it", 0, entity.id)
    }

    /**
     * Test Case 3: Positive case - Two entities with identical fields are equal
     * Verifies data-class structural equality
     */
    @Test
    fun testNoteEntityEquality_SameFields_AreEqual() {
        // Arrange
        val entity1 = NoteEntity(id = 1, title = "Title", createdAt = 100L)
        val entity2 = NoteEntity(id = 1, title = "Title", createdAt = 100L)

        // Assert
        assertEquals("Entities with same fields should be equal", entity1, entity2)
    }

    /**
     * Test Case 4: Negative case - Two entities with different IDs are not equal
     * Verifies that id difference produces inequality
     */
    @Test
    fun testNoteEntityInequality_DifferentIds_AreNotEqual() {
        // Arrange
        val entity1 = NoteEntity(id = 1, title = "Same Title", createdAt = 100L)
        val entity2 = NoteEntity(id = 2, title = "Same Title", createdAt = 100L)

        // Assert
        assertNotEquals("Entities with different IDs should not be equal", entity1, entity2)
    }

    /**
     * Test Case 5: Edge case - Empty title is accepted
     * Verifies NoteEntity accepts empty string title
     */
    @Test
    fun testNoteEntityEmptyTitle_IsAccepted() {
        // Act
        val entity = NoteEntity(id = 3, title = "", createdAt = 200L)

        // Assert
        assertEquals("Empty title should be stored as empty string", "", entity.title)
    }

    /**
     * Test Case 6: Edge case - Very long title is accepted
     * Verifies NoteEntity accepts titles of 500 characters
     */
    @Test
    fun testNoteEntityLongTitle_IsAccepted() {
        // Arrange
        val longTitle = "A".repeat(500)

        // Act
        val entity = NoteEntity(id = 4, title = longTitle, createdAt = 300L)

        // Assert
        assertEquals("Long title length should be 500", 500, entity.title.length)
        assertEquals("Long title should be stored correctly", longTitle, entity.title)
    }

    /**
     * Test Case 7: Edge case - Timestamp of zero is valid
     * Verifies boundary value for createdAt field
     */
    @Test
    fun testNoteEntityZeroTimestamp_IsValid() {
        // Act
        val entity = NoteEntity(id = 6, title = "Zero Time", createdAt = 0L)

        // Assert
        assertEquals("CreatedAt of 0 should be stored", 0L, entity.createdAt)
    }

    /**
     * Test Case 8: Positive case - NoteEntity instance is not null after construction
     * Basic sanity check for object creation
     */
    @Test
    fun testNoteEntityCreation_IsNotNull() {
        // Act
        val entity = NoteEntity(title = "Sanity Check")

        // Assert
        assertNotNull("NoteEntity should not be null after construction", entity)
    }
}
